FROM python:3.13.0-slim-buster


# Set the working directory to /app
WORKDIR /app

# Pip: Install requirements
COPY requirements.txt /tmp/requirements.txt
RUN pip3 install --upgrade pip
RUN pip3 install -r /tmp/requirements.txt
