pip3 install pandas
pip3 install tkinter
pip3 install bs4
pip3 install selenium 
pip3 install docx
pip3 install python-docx
pip3 install pywin32
pip3 install openpyxl
pip3 install psutil
pip3 install ocx.opc